apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: proxy
        env:
        - name: CONNECTION_STRING
          value: jdbc:mariadb://mariadb.default.svc.cluster.local:3306/whitelist?user=root&password=password
        ports:
        - containerPort: 25565
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
