apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy
  name: proxy
spec:
  ports:
    - name: proxy
      nodePort: 30000
      port: 25565
      protocol: TCP
      targetPort: 25565
  selector:
    app: proxy
  type: NodePort
