kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-infra

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 25565
      - containerPort: 30001
        hostPort: 30001
