apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: local-infrastructure
build:
  artifacts:
  - image: proxy
    context: kryo/proxy
    docker:
      dockerfile: Dockerfile
  - image: server
    context: kryo/server
    docker:
      dockerfile: Dockerfile
  - image: whitelist-bot
    context: kryo/whitelist-bot
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - manifests/proxy/*.yaml
    - manifests/server/*.yaml
    - manifests/whitelist-bot/*.yaml
